baseURL = 'https://goos.photos/'
languageCode = 'en-us'
title = 'goos.photos'
theme = 'gallery'
disableKinds = ['taxonomy','term']
enableRobotsTXT = true


[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[params]
  defaultTheme = "dark"
